### ISSUE TITLE
Accessing to the account on the "cloudron" realm: Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by marc-farre** [njsubedi/cloudron-keycloak#2] opened 2022-03-25 14:23 UTC
It is not possible to access to our account when logged in to a user on cloudron realm.

On master it works: https://keycloak.my-cloudron.org/realms/master/account/
But not on cloudron: https://keycloak.my-cloudron.org/realms/cloudron/account/

Error message: `Invalid parameter: redirect_uri`

Same problem when using impersonation. Go to:
https://keycloak.my-cloudron.org/admin/master/console/#/realms/cloudron/users
Choose a user and clic the "Impersonate" button.
You arrive on https://keycloak.my-cloudron.org/realms/cloudron/protocol/openid-connect/auth?client_id=account-console&redirect_uri=https%3A%2F%2Fkeycloak.my-cloudron.org%2Frealms%2Fcloudron ....
And the same  `Invalid parameter: redirect_uri` appears (but impersonation works).

This problem is not related to a client. Clients works and don't have any redirection problem.

PS: in our case, the `cloudron` realm has been renamed to another name, but I doubt this could have an impact.

**Comment by njsubedi** [comment] 2022-03-31 13:32
I tried to reproduce the issue but I couldn't. Could you share some kind of screenshot / screen recording showing the problem? Also, the issue might have been fixed in Keycloak 17.0.1 because I only tested on the latest installation.
Thanks for reporting the issue!

**Comment by marc-farre** [comment] 2022-04-07 14:17
Thanks for your answer. The problem came from renaming the realm. When I rename it to the original name `cloudron` it works well!

**Closed as completed** 2023-01-09 11:29 UTC
